# Generated by Django 5.1.4 on 2025-01-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialprofile',
            old_name='user',
            new_name='profile_user',
        ),
    ]
