# Generated by Django 5.1.4 on 2025-01-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_financialprofile_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialProfile',
        ),
    ]
