# Generated by Django 5.1.4 on 2025-01-03 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_financialprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CibilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cibil_score', models.PositiveIntegerField()),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cibil_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
