# Generated by Django 5.1.4 on 2025-01-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_bankdata_applicant_alter_cibildata_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='home.userprofile'),
        ),
    ]
